apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: leaflink-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dhenob/flask-k8s-gitops.git'
    path: argocd/apps
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
