name: Release Pipeline

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The Docker image version to release'
        required: true

jobs:
  update-helm-chart:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update Helm values file
      run: |
        echo "Updating image tag to ${{ github.event.inputs.version }}"
        sed -i "s/tag: .*/tag: \"${{ github.event.inputs.version }}\"/" helm-chart/values.yaml

    - name: Setup Git config
      run: |
        git config user.name 'github-actions'
        git config user.email 'github-actions@github.com'

    - name: Commit changes
      run: |
        git add helm-chart/values.yaml
        git commit -m "Update Helm chart for release ${{ github.event.inputs.version }}"
        git status

    - name: Push changes
      run: |
        git remote set-url origin https://${ secrets.MY_PERSONAL_TOKEN }@github.com/dhenob/flask-k8s-gitops.git
        git push origin HEAD:main
